### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/ECE461-Software-Engineering#22]
This task involves setting up parallelization for each metric and URL. Additionally, during this step, the order of execution will be rearranged to minimize downtime.

- [x] break classes into separate files
- [x] review each classes Complexity
- [x] review API calls being made and look for consolidation points
- [x] prune unused libraries
- [x] add getRepoData to parent class

**Comment by galaxybomb23** [comment]
This should not have been linked to #34

**Comment by Coop8** [comment]
Ramp up does local stuff now so API calls are down from 91 -> 0!. Cleaned up unused libraries.
