### ISSUE TITLE
Maintainabilty Testing not present.

### ISSUE THREAD

**Issue by RushilShaw** [galaxybomb23/ECE461-Software-Engineering#33]
Maintainability Testing is not present in the cli.ts file, while the tests for the other metrics are merged into main. Without this we cannot ensure that the maintainability function works and functions in an efficient and time-sensitive manner.

I plan to write the testing function, create a pull request following our standard procedures, then merge with main.

[Edited]

**Comment by galaxybomb23** [comment]
This issue does not follow the standard for issues. Please clearly define the issue you are facing, or work you plan to do. If you plan to do the work yourself, assign yourself to the issue and apply the relevant tags.
