### ISSUE TITLE
Initialize inital repo structure and basic script

### ISSUE THREAD

**Issue by galaxybomb23** [galaxybomb23/ECE461-Software-Engineering#9]
#### 1.1 **Initialize the Project**
- **Tools Required:**
  - Node.js and npm (Node Package Manager)
  - TypeScript
  - Git for version control

- **Steps:**
  1. **Install Node.js and npm** if not already installed.
    
     ```bash
     #Linux
      sudo apt update
      sudo apt install nodejs

      #mac
      brew install node
     ```
  2. **Initialize a Node.js project** and install TypeScript.
     ```bash
     npm init -y
     npm install typescript --save-dev
     ```
  3. **Set up the TypeScript configuration** by generating a `tsconfig.json` file.
     ```bash
     npx tsc --init
     ```

  4. **Define the project structure:**
     - `/src`: Source files (TypeScript)
     - `/test`: Test files
     - `/bin`: Executable scripts, including the `run` script
     - `/docs`: Documentation
     - `/logs`: Log files
     - `/config`: Configuration files

- [x] **Deliverable:** A fully initialized project scaffold with TypeScript support.

#### 2.1 **Create the Executable Script**
- **Script Name:** `run`
- **Location:** Root directory
- **Permissions:** Make sure the script is executable.
  ```bash
  chmod +x run
  ```

#### 2.2 **Implement Basic Commands**
- **Commands:**
  - `install`: Installs dependencies.
  - `URL_FILE`: Processes a list of module URLs.
  - `test`: Runs the test suite.
  - `chelp`: print the cli command list
  - `help`: prints the command list

- [x] **Deliverable:** A basic CLI that can install dependencies, process URLs, and run tests.

**Comment by galaxybomb23** [comment]
The CLI doesn't do full processing of the URLs. Those will be in separate issues

**Comment by RushilShaw** [comment]
Noice
